// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#define expansionMatrix uint2x2(3, 1, 1 ,3)

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

uint2 offSet;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    
    float4 col = float4(id.x & id.y, (id.x & 15) / 15.0, (id.y & 15) / 15.0, 0.0);
    Result[mul(expansionMatrix, id.xy) + offSet] = col;
}
